name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build NextJS app based on branch
        run: |
            npm run build

  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN }}
        
      - name: Define Docker build mode
        id: mode
        run: |
         if [ "${{ github.ref_name }}" = "main" ]; then
            echo "mode=prod" >> $GITHUB_OUTPUT
         else
            echo "mode=dev" >> $GITHUB_OUTPUT
         fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
         context: ./
         file: ./build/Dockerfile
         push: true
         build-args: |
            MODE=${{ steps.mode.outputs.mode }}
         tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ github.ref_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ github.ref_name }}:latest

