name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        
      - name: Set up environment file based on branch
        run: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Using production environment"
            else
            echo "Using development environment"
            cp .env.dev .env.production
            fi

      - name: Build NextJS app based on branch
        run: |
            npm run build

  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN }}

      - name: Build and push Next.js app Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./build/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ github.ref_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ github.ref_name }}:latest

